---
- name: install unzip
  apt: name=unzip state=present

- name: download consul
  get_url: url=https://dl.bintray.com/mitchellh/consul/0.4.0_linux_amd64.zip dest=/tmp/consul.zip

- name: unzip consul
  command: unzip -n /tmp/consul.zip -d /usr/local/bin

- name: remove consul package
  file: path=/tmp/consul.zip state=absent

- name: create consul config folder
  file: path=/etc/consul.d state=directory

- name: copy supervisor configuration
  template: src={{ supervisor_configuration_file }} dest=/etc/supervisor/conf.d/consul.conf

- name: stop supervisor
  service: name=supervisor state=stopped

- name: start supervisor
  service: name=supervisor state=started
