directory: ~/Music/
plugins: chroma rewrite inline lastgenre lyrics scrub fetchart embedart discogs zero ftintitle duplicates missing
original_date: yes

paths:
  default: $albumartist/$year - $album%aunique{}/$track - $title

import:
  move: yes
  languages:
    - en

acoustid:
  apikey: 14bfpR0w

lastgenre:
  canonical: ''

zero:
  fields: comments
