# Automatically migrated from legacy .beetsconfig.

directory: /media/data/Music/.recent
plugins: chroma rewrite inline lastgenre scrub fetchart embedart

import:
    move: true

pathfields:
    subdirectory: 'u''yes'' if

        disctotal > 1 else u'''''

paths:
    default: $albumartist/$year - $album%aunique{}/%if{$subdirectory,disc $disc}/$track - $title

acoustid:
    apikey: 14bfpR0w
