---
- name: install zsh on osx
  homebrew: name="zsh" state="present"
  when: ansible_os_family == "Darwin"

- name: copy files
  synchronize: dest="{{ home }}/.{{ item }}" src="{{ base_dir }}/files/home/antonio/{{ item }}"
  when: inventory_hostname != 'localhost'
  with_items: zsh_files

- name: link files
  file: path="{{ home }}/.{{ item }}" src="{{ base_dir }}/files/home/antonio/{{ item }}" state="link"
  when: inventory_hostname == 'localhost'
  with_items: zsh_files

- name: change default shell
  user: name="{{ ansible_user_id }}" shell="/bin/zsh"
  sudo: yes
  when: ansible_os_family == "Linux"
