---
- name: install zsh on osx
  homebrew: name="zsh" state="present"
  when: ansible_os_family == "Darwin"

- name: copy files
  copy: dest="{{ home }}/.{{ item }}" src="{{ base_dir }}/files/home/antonio/{{ item }}"
  with_items:
    - zshrc
    - zshenv

- name: set up ~/.zsh
  synchronize: dest="{{ home }}/.zsh" src="{{ base_dir }}/files/home/antonio/zsh/"

- name: add github.com to known_hosts
  lineinfile:
    dest="{{ home }}/.ssh/known_hosts" create="yes" regexp="^github\\.com"
    line="github.com,192.30.252.131 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

- name: clone external projects
  git: repo="{{ item.value.repo }}" dest="{{ item.value.dest }}"
  with_dict: zsh_projects

- name: change default shell
  user: name="{{ ansible_user_id }}" shell="/bin/zsh"
  sudo: yes
  when: ansible_os_family == "Linux"
