---
- name: install zsh on osx
  homebrew: name="zsh" state="present"
  when: ansible_os_family == "Darwin"

- name: copy files
  copy: dest="{{ home }}/.{{ item }}" src="{{ base_dir }}/files/home/antonio/{{ item }}"
  with_items:
    - zshrc
    - zshenv

- name: set up ~/.zsh
  synchronize: dest="{{ home }}/.zsh" src="{{ base_dir }}/files/home/antonio/zsh/"

- name: checkout external projects
  git: repo="{{ item.value.repo }}" dest="{{ item.value.dest }}"
  with_dict: zsh_projects
