---
- name: add tmate tap
  homebrew_tap: tap="nviennot/tmate"

- name: install homebrew packages
  homebrew: name="{{ item }}" state="present"
  with_items:
    - ack
    - awscli
    - brew-cask
    - chromaprint
    - chruby
    - colordiff
    - coreutils
    - ctags
    - curl
    - dnsmasq
    - docker
    - dtrx
    - exiftool
    - fasd
    - faac
    - fdupes
    - ffmpeg
    - findutils
    - fzf
    - git
    - gnupg2
    - gpg-agent
    - imagemagick
    - jq
    - lastpass-cli
    - lua
    - ncdu
    - netcat
    - nmap
    - ntfs-3g
    - p7zip
    - pass
    - pigz
    - privoxy
    - pstree
    - ranger
    - reattach-to-user-namespace
    - ruby-install
    - sshfs
    - syncthing
    - the_silver_searcher
    - tmate
    - tree
    - unrar
    - wakeonlan
    - watch
    - wget
    - youtube-dl
    - zsh

- name: install global
  homebrew: name="global" state="present" install_options="--with-exuberant-ctags --with-pygments"

- name: install homebrew cask packages
  homebrew_cask: name="{{ item }}" state="present"
  with_items:
    - alfred
    - anki
    - atom
    - boxer
    - calibre
    - consul
    - consul-template
    - crashplan
    - dash
    - dropbox
    - hammerspoon
    - firefox
    - flux
    - gog-galaxy
    - google-chrome
    - iterm2
    - karabiner
    - kindle
    - lastfm
    - lastpass
    - league-of-legends
    - lyn
    - minecraft
    - picasa
    - screenhero
    - scummvm
    - skype
    - slack
    - spotify
    - telegram
    - the-unarchiver
    - totalspaces
    - transmission
    - vagrant
    - vault
    - virtualbox
    - viscosity
    - vlc
    - wesnoth
    - wireshark
    - yacreader

- name: pip packages
  pip: name="{{ item }}"
  with_items:
    - glances

# - name: set up the environment
#   copy: src="com.santosvelasco.environment.plist" dest="{{ home }}/Library/LaunchAgents/com.santosvelasco.environment.plist"

# - name: load environment launch agent
#   command: "launchctl load -w ~/Library/LaunchAgents/com.santosvelasco.environment"
