---
- name: install emacs on osx
  homebrew: name="emacs" state="present" install_options="use-git-head,with-gnutls,cocoa,with-imagemagick"

- name: copy the service file
  copy: src=org.gnu.emacs.plist dest=~/Library/LaunchAgents/org.gnu.emacs.plist

- name: enable the service
  command: launchctl load -w ~/Library/LaunchAgents/org.gnu.emacs.plist
