# prompts and themes
autoload -Uz promptinit
setopt promptsubst
promptinit

# colors
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
autoload -U colors && colors

# zmv
autoload -U zmv

# path
typeset -U PATH

# run-help
autoload -U run-help
export HELPDIR=~/.zsh/help

set -o emacs

# history
export HISTFILE=$HOME/.zhistory
export SAVEHIST=2000
export HISTSIZE=2000
setopt extended_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt inc_append_history
setopt share_history

# globbing
setopt extended_glob

# ux
export WORDCHARS='*?_-[]~=&;!#$%^(){}<>'
setopt no_flowcontrol

# time commands that run for a long time
export REPORTTIME=5

source ~/.zsh/aliases.zsh
source ~/.zsh/git.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/wakeonlan.zsh
source ~/.zsh/dotenv.zsh
source ~/.zsh/keys.zsh
source ~/.zsh/go.zsh
source ~/.zsh/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/history-substring-search.zsh
source ~/.zsh/modules/k/k.sh
source ~/.zsh/completions.zsh
source ~/.zsh/fasd.zsh
source ~/.fzf.zsh
source ~/.zsh/modules/hhighlighter/h.sh

[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

compinit # Loading completions as late as possible

prompt antonio

if $(which chruby > /dev/null); then
  chruby 2.1.4
fi

[[ -n $DISPLAY ]] && [[ -z $TMUX ]] && tmux

if [ "$(uname)" != "Darwin" ]; then
  (which gpg-agent && eval $(gpg-agent --daemon)) >/dev/null 2>&1
fi

if [[ -n $TMUX ]]; then
  window_name=$(tmux display -p "#W")
  if [[ $window_name =~ "reattach" ]]; then
    printf '\033kshell\033\\'
  fi
fi
